spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev                      #开发环境
  application:
    name: microservicecloud-config-ty-dev
---
spring:
  profils: test                          #测试环境
  application:
    name: microservicecloud-config-ty-test