spring:
   application: 
      name: microservicecloud-config-eureka-client   #需要从github上读取资源名称，注意没有yml后缀名
   profiles: dev           

eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false  #表示不想注册中心注册自己
    fetch-registry: false          #表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
       defaultZone: http://eureka7001.com:7001/eureka/
---
server：
   port: 7001

spring:
   application: 
      name: microservicecloud-config-eureka-client   #需要从github上读取资源名称，注意没有yml后缀名
   profiles: test             #本次访问的配置项

eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false  #表示不想注册中心注册自己
    fetch-registry: false          #表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
       defaultZone: http://eureka7001.com:7001/eureka/